// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Piclemx.Opensearch
{
    /// <summary>
    /// Provides an OpenSearch dashboard tenant resource. Please refer to the OpenSearch documentation for details.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Opensearch = Piclemx.Opensearch;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create a tenant
    ///     var test = new Opensearch.DashboardTenant("test", new()
    ///     {
    ///         Description = "test tenant",
    ///         TenantName = "test",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import opensearch:index/dashboardTenant:DashboardTenant writer test
    /// ```
    /// </summary>
    [OpensearchResourceType("opensearch:index/dashboardTenant:DashboardTenant")]
    public partial class DashboardTenant : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Description of the tenant.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("index")]
        public Output<string> Index { get; private set; } = null!;

        /// <summary>
        /// The name of the tenant.
        /// </summary>
        [Output("tenantName")]
        public Output<string> TenantName { get; private set; } = null!;


        /// <summary>
        /// Create a DashboardTenant resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DashboardTenant(string name, DashboardTenantArgs args, CustomResourceOptions? options = null)
            : base("opensearch:index/dashboardTenant:DashboardTenant", name, args ?? new DashboardTenantArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DashboardTenant(string name, Input<string> id, DashboardTenantState? state = null, CustomResourceOptions? options = null)
            : base("opensearch:index/dashboardTenant:DashboardTenant", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/piclemx/pulumi-opensearch",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DashboardTenant resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DashboardTenant Get(string name, Input<string> id, DashboardTenantState? state = null, CustomResourceOptions? options = null)
        {
            return new DashboardTenant(name, id, state, options);
        }
    }

    public sealed class DashboardTenantArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the tenant.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the tenant.
        /// </summary>
        [Input("tenantName", required: true)]
        public Input<string> TenantName { get; set; } = null!;

        public DashboardTenantArgs()
        {
        }
        public static new DashboardTenantArgs Empty => new DashboardTenantArgs();
    }

    public sealed class DashboardTenantState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the tenant.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("index")]
        public Input<string>? Index { get; set; }

        /// <summary>
        /// The name of the tenant.
        /// </summary>
        [Input("tenantName")]
        public Input<string>? TenantName { get; set; }

        public DashboardTenantState()
        {
        }
        public static new DashboardTenantState Empty => new DashboardTenantState();
    }
}
