# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

awsAccessKey: Optional[str]
"""
The access key for use with AWS OpenSearch Service domains
"""

awsAssumeRoleArn: Optional[str]
"""
Amazon Resource Name of an IAM Role to assume prior to making AWS API calls.
"""

awsAssumeRoleExternalId: Optional[str]
"""
External ID configured in the IAM policy of the IAM Role to assume prior to making AWS API calls.
"""

awsProfile: Optional[str]
"""
The AWS profile for use with AWS OpenSearch Service domains
"""

awsRegion: Optional[str]
"""
The AWS region for use in signing of AWS OpenSearch requests. Must be specified in order to use AWS URL signing with AWS
OpenSearch endpoint exposed on a custom DNS domain.
"""

awsSecretKey: Optional[str]
"""
The secret key for use with AWS OpenSearch Service domains
"""

awsSignatureService: Optional[str]
"""
AWS service name used in the credential scope of signed requests to OpenSearch.
"""

awsToken: Optional[str]
"""
The session token for use with AWS OpenSearch Service domains
"""

cacertFile: Optional[str]
"""
A Custom CA certificate
"""

clientCertPath: Optional[str]
"""
A X509 certificate to connect to OpenSearch
"""

clientKeyPath: Optional[str]
"""
A X509 key to connect to OpenSearch
"""

healthcheck: Optional[bool]
"""
Set the client healthcheck option for the OpenSearch client. Healthchecking is designed for direct access to the
cluster.
"""

hostOverride: Optional[str]
"""
If provided, sets the 'Host' header of requests and the 'ServerName' for certificate validation to this value. See the
documentation on connecting to OpenSearch via an SSH tunnel.
"""

insecure: Optional[bool]
"""
Disable SSL verification of API calls
"""

opensearchVersion: Optional[str]
"""
OpenSearch Version
"""

password: Optional[str]
"""
Password to use to connect to OpenSearch using basic auth
"""

proxy: Optional[str]
"""
Proxy URL to use for requests to OpenSearch.
"""

signAwsRequests: Optional[bool]
"""
Enable signing of AWS OpenSearch requests. The `url` must refer to AWS ES domain (`*.<region>.es.amazonaws.com`), or
`aws_region` must be specified explicitly.
"""

sniff: Optional[bool]
"""
Set the node sniffing option for the OpenSearch client. Client won't work with sniffing if nodes are not routable.
"""

token: Optional[str]
"""
A bearer token or ApiKey for an Authorization header, e.g. Active Directory API key.
"""

tokenName: Optional[str]
"""
The type of token, usually ApiKey or Bearer
"""

url: Optional[str]
"""
OpenSearch URL
"""

username: Optional[str]
"""
Username to use to connect to OpenSearch using basic auth
"""

versionPingTimeout: Optional[int]
"""
Version ping timeout in seconds
"""

