// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/piclemx/pulumi-opensearch/sdk/go/opensearch/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The access key for use with AWS OpenSearch Service domains
func GetAwsAccessKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsAccessKey")
}

// Amazon Resource Name of an IAM Role to assume prior to making AWS API calls.
func GetAwsAssumeRoleArn(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsAssumeRoleArn")
}

// External ID configured in the IAM policy of the IAM Role to assume prior to making AWS API calls.
func GetAwsAssumeRoleExternalId(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsAssumeRoleExternalId")
}

// The AWS profile for use with AWS OpenSearch Service domains
func GetAwsProfile(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsProfile")
}

// The AWS region for use in signing of AWS OpenSearch requests. Must be specified in order to use AWS URL signing with AWS
// OpenSearch endpoint exposed on a custom DNS domain.
func GetAwsRegion(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsRegion")
}

// The secret key for use with AWS OpenSearch Service domains
func GetAwsSecretKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsSecretKey")
}

// AWS service name used in the credential scope of signed requests to OpenSearch.
func GetAwsSignatureService(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsSignatureService")
}

// The session token for use with AWS OpenSearch Service domains
func GetAwsToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:awsToken")
}

// A Custom CA certificate
func GetCacertFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:cacertFile")
}

// A X509 certificate to connect to OpenSearch
func GetClientCertPath(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:clientCertPath")
}

// A X509 key to connect to OpenSearch
func GetClientKeyPath(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:clientKeyPath")
}

// Set the client healthcheck option for the OpenSearch client. Healthchecking is designed for direct access to the
// cluster.
func GetHealthcheck(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "opensearch:healthcheck")
}

// If provided, sets the 'Host' header of requests and the 'ServerName' for certificate validation to this value. See the
// documentation on connecting to OpenSearch via an SSH tunnel.
func GetHostOverride(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:hostOverride")
}

// Disable SSL verification of API calls
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "opensearch:insecure")
}

// OpenSearch Version
func GetOpensearchVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:opensearchVersion")
}

// Password to use to connect to OpenSearch using basic auth
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:password")
}

// Proxy URL to use for requests to OpenSearch.
func GetProxy(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:proxy")
}

// Enable signing of AWS OpenSearch requests. The `url` must refer to AWS ES domain (`*.<region>.es.amazonaws.com`), or
// `awsRegion` must be specified explicitly.
func GetSignAwsRequests(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "opensearch:signAwsRequests")
}

// Set the node sniffing option for the OpenSearch client. Client won't work with sniffing if nodes are not routable.
func GetSniff(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "opensearch:sniff")
}

// A bearer token or ApiKey for an Authorization header, e.g. Active Directory API key.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:token")
}

// The type of token, usually ApiKey or Bearer
func GetTokenName(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:tokenName")
}

// OpenSearch URL
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:url")
}

// Username to use to connect to OpenSearch using basic auth
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "opensearch:username")
}

// Version ping timeout in seconds
func GetVersionPingTimeout(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "opensearch:versionPingTimeout")
}
