# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['IsmPolicyArgs', 'IsmPolicy']

@pulumi.input_type
class IsmPolicyArgs:
    def __init__(__self__, *,
                 body: pulumi.Input[str],
                 policy_id: pulumi.Input[str],
                 primary_term: Optional[pulumi.Input[int]] = None,
                 seq_no: Optional[pulumi.Input[int]] = None):
        """
        The set of arguments for constructing a IsmPolicy resource.
        :param pulumi.Input[str] body: The policy document.
        :param pulumi.Input[str] policy_id: The id of the ISM policy.
        :param pulumi.Input[int] primary_term: The primary term of the ISM policy version.
        :param pulumi.Input[int] seq_no: The sequence number of the ISM policy version.
        """
        pulumi.set(__self__, "body", body)
        pulumi.set(__self__, "policy_id", policy_id)
        if primary_term is not None:
            pulumi.set(__self__, "primary_term", primary_term)
        if seq_no is not None:
            pulumi.set(__self__, "seq_no", seq_no)

    @property
    @pulumi.getter
    def body(self) -> pulumi.Input[str]:
        """
        The policy document.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: pulumi.Input[str]):
        pulumi.set(self, "body", value)

    @property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> pulumi.Input[str]:
        """
        The id of the ISM policy.
        """
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "policy_id", value)

    @property
    @pulumi.getter(name="primaryTerm")
    def primary_term(self) -> Optional[pulumi.Input[int]]:
        """
        The primary term of the ISM policy version.
        """
        return pulumi.get(self, "primary_term")

    @primary_term.setter
    def primary_term(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "primary_term", value)

    @property
    @pulumi.getter(name="seqNo")
    def seq_no(self) -> Optional[pulumi.Input[int]]:
        """
        The sequence number of the ISM policy version.
        """
        return pulumi.get(self, "seq_no")

    @seq_no.setter
    def seq_no(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "seq_no", value)


@pulumi.input_type
class _IsmPolicyState:
    def __init__(__self__, *,
                 body: Optional[pulumi.Input[str]] = None,
                 policy_id: Optional[pulumi.Input[str]] = None,
                 primary_term: Optional[pulumi.Input[int]] = None,
                 seq_no: Optional[pulumi.Input[int]] = None):
        """
        Input properties used for looking up and filtering IsmPolicy resources.
        :param pulumi.Input[str] body: The policy document.
        :param pulumi.Input[str] policy_id: The id of the ISM policy.
        :param pulumi.Input[int] primary_term: The primary term of the ISM policy version.
        :param pulumi.Input[int] seq_no: The sequence number of the ISM policy version.
        """
        if body is not None:
            pulumi.set(__self__, "body", body)
        if policy_id is not None:
            pulumi.set(__self__, "policy_id", policy_id)
        if primary_term is not None:
            pulumi.set(__self__, "primary_term", primary_term)
        if seq_no is not None:
            pulumi.set(__self__, "seq_no", seq_no)

    @property
    @pulumi.getter
    def body(self) -> Optional[pulumi.Input[str]]:
        """
        The policy document.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "body", value)

    @property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> Optional[pulumi.Input[str]]:
        """
        The id of the ISM policy.
        """
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "policy_id", value)

    @property
    @pulumi.getter(name="primaryTerm")
    def primary_term(self) -> Optional[pulumi.Input[int]]:
        """
        The primary term of the ISM policy version.
        """
        return pulumi.get(self, "primary_term")

    @primary_term.setter
    def primary_term(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "primary_term", value)

    @property
    @pulumi.getter(name="seqNo")
    def seq_no(self) -> Optional[pulumi.Input[int]]:
        """
        The sequence number of the ISM policy version.
        """
        return pulumi.get(self, "seq_no")

    @seq_no.setter
    def seq_no(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "seq_no", value)


class IsmPolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 body: Optional[pulumi.Input[str]] = None,
                 policy_id: Optional[pulumi.Input[str]] = None,
                 primary_term: Optional[pulumi.Input[int]] = None,
                 seq_no: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        """
        Provides an OpenSearch Index State Management (ISM) policy. Please refer to the OpenSearch ISM documentation for details.

        ## Example Usage

        ```python
        import pulumi
        import piclemx_pulumi_opensearch as opensearch

        # Create an ISM policy
        cleanup = opensearch.IsmPolicy("cleanup",
            policy_id="delete_after_15d",
            body=(lambda path: open(path).read())(f"{path['module']}/policies/delete_after_15d.json"))
        ```

        ## Import

        ```sh
         $ pulumi import opensearch:index/ismPolicy:IsmPolicy cleanup delete_after_15d
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] body: The policy document.
        :param pulumi.Input[str] policy_id: The id of the ISM policy.
        :param pulumi.Input[int] primary_term: The primary term of the ISM policy version.
        :param pulumi.Input[int] seq_no: The sequence number of the ISM policy version.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IsmPolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides an OpenSearch Index State Management (ISM) policy. Please refer to the OpenSearch ISM documentation for details.

        ## Example Usage

        ```python
        import pulumi
        import piclemx_pulumi_opensearch as opensearch

        # Create an ISM policy
        cleanup = opensearch.IsmPolicy("cleanup",
            policy_id="delete_after_15d",
            body=(lambda path: open(path).read())(f"{path['module']}/policies/delete_after_15d.json"))
        ```

        ## Import

        ```sh
         $ pulumi import opensearch:index/ismPolicy:IsmPolicy cleanup delete_after_15d
        ```

        :param str resource_name: The name of the resource.
        :param IsmPolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IsmPolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 body: Optional[pulumi.Input[str]] = None,
                 policy_id: Optional[pulumi.Input[str]] = None,
                 primary_term: Optional[pulumi.Input[int]] = None,
                 seq_no: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IsmPolicyArgs.__new__(IsmPolicyArgs)

            if body is None and not opts.urn:
                raise TypeError("Missing required property 'body'")
            __props__.__dict__["body"] = body
            if policy_id is None and not opts.urn:
                raise TypeError("Missing required property 'policy_id'")
            __props__.__dict__["policy_id"] = policy_id
            __props__.__dict__["primary_term"] = primary_term
            __props__.__dict__["seq_no"] = seq_no
        super(IsmPolicy, __self__).__init__(
            'opensearch:index/ismPolicy:IsmPolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            body: Optional[pulumi.Input[str]] = None,
            policy_id: Optional[pulumi.Input[str]] = None,
            primary_term: Optional[pulumi.Input[int]] = None,
            seq_no: Optional[pulumi.Input[int]] = None) -> 'IsmPolicy':
        """
        Get an existing IsmPolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] body: The policy document.
        :param pulumi.Input[str] policy_id: The id of the ISM policy.
        :param pulumi.Input[int] primary_term: The primary term of the ISM policy version.
        :param pulumi.Input[int] seq_no: The sequence number of the ISM policy version.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IsmPolicyState.__new__(_IsmPolicyState)

        __props__.__dict__["body"] = body
        __props__.__dict__["policy_id"] = policy_id
        __props__.__dict__["primary_term"] = primary_term
        __props__.__dict__["seq_no"] = seq_no
        return IsmPolicy(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def body(self) -> pulumi.Output[str]:
        """
        The policy document.
        """
        return pulumi.get(self, "body")

    @property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> pulumi.Output[str]:
        """
        The id of the ISM policy.
        """
        return pulumi.get(self, "policy_id")

    @property
    @pulumi.getter(name="primaryTerm")
    def primary_term(self) -> pulumi.Output[int]:
        """
        The primary term of the ISM policy version.
        """
        return pulumi.get(self, "primary_term")

    @property
    @pulumi.getter(name="seqNo")
    def seq_no(self) -> pulumi.Output[int]:
        """
        The sequence number of the ISM policy version.
        """
        return pulumi.get(self, "seq_no")

