// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides an OpenSearch channel configuration. Please refer to the OpenSearch channel configuration documentation for details.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as opensearch from "@piclemx/pulumi-opensearch";
 *
 * // Create a channel configuration
 * const configuration1 = new opensearch.ChannelConfiguration("configuration1", {body: `{
 *   "config_id": "configuration_1",
 *   "config": {
 *     "name": "name",
 *     "description" : "description",
 *     "config_type" : "slack",
 *     "is_enabled" : true,
 *     "slack": {
 *       "url": "https://sample-slack-webhook"
 *     }
 *   }
 * }
 *
 * `});
 * ```
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import opensearch:index/channelConfiguration:ChannelConfiguration configuration_1 configuration_1
 * ```
 */
export class ChannelConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing ChannelConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ChannelConfigurationState, opts?: pulumi.CustomResourceOptions): ChannelConfiguration {
        return new ChannelConfiguration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'opensearch:index/channelConfiguration:ChannelConfiguration';

    /**
     * Returns true if the given object is an instance of ChannelConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChannelConfiguration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChannelConfiguration.__pulumiType;
    }

    /**
     * The channel configuration document
     */
    public readonly body!: pulumi.Output<string>;

    /**
     * Create a ChannelConfiguration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChannelConfigurationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ChannelConfigurationArgs | ChannelConfigurationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ChannelConfigurationState | undefined;
            resourceInputs["body"] = state ? state.body : undefined;
        } else {
            const args = argsOrState as ChannelConfigurationArgs | undefined;
            if ((!args || args.body === undefined) && !opts.urn) {
                throw new Error("Missing required property 'body'");
            }
            resourceInputs["body"] = args ? args.body : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ChannelConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ChannelConfiguration resources.
 */
export interface ChannelConfigurationState {
    /**
     * The channel configuration document
     */
    body?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ChannelConfiguration resource.
 */
export interface ChannelConfigurationArgs {
    /**
     * The channel configuration document
     */
    body: pulumi.Input<string>;
}
